### Obtener todos los clientes
GET http://localhost:3000/clients
Content-Type: application/json

###

### Obtener un cliente por RFC
GET http://localhost:3000/clients/21350249

###

### Agregar un nuevo cliente
POST http://localhost:3000/clients
Content-Type: application/json

{
  "rfc": "21350249",
  "first_name": "Jesus",
  "last_name": "Alberto",
  "birth_date": "2002-12-17",
  "gender": "M",
  "phone_number": "2871207686",
  "email": "jesus@equipo7.com",
  "address": "Colonia La Piragua, Tuxtepec, Oaxaca"
}

###

### Actualizar un cliente existente
PUT http://localhost:3000/clients/2132131
Content-Type: application/json

{
  "first_name": "Jesus",
  "last_name": "Alberto",
  "birth_date": "2002-12-17",
  "gender": "M",
  "phone_number": "2871207686",
  "email": "jesusalb@equipo7.com",
  "address": "Colonia la piragua, Tuxtepec, Oaxaca"
}


### Eliminar un cliente
DELETE http://localhost:3000/clients/21350249

