### Obtener todos los clientes
GET http://localhost:3000/clients
Content-Type: application/json

###

### Obtener un cliente por RFC
GET http://localhost:3000/clients/21350239

###

### Agregar un nuevo cliente
POST http://localhost:3000/clients
Content-Type: application/json

{
  "rfc": "21350239",
  "first_name": "Uriel",
  "last_name": "Castillo",
  "birth_date": "2003-04-04",
  "gender": "M",
  "phone_number": "2871541652",
  "email": "uriel@equipo7.com",
  "address": "Colonia el progreso, Tuxtepec, Oaxaca"
}

###

### Actualizar un cliente existente
PUT http://localhost:3000/clients/21350239
Content-Type: application/json

{
  "first_name": "Jesus",
  "last_name": "Garcia",
  "birth_date": "2003-12-17",
  "gender": "M",
  "phone_number": "2871005665",
  "email": "jesus@equipo7.com",
  "address": "Colonia la piragua, Tuxtepec, Oaxaca"
}


### Eliminar un cliente
DELETE http://localhost:3000/clients/21350239

