### Obtener todas las ventas (GET)
GET http://localhost:3000/sales

### Obtener una venta por ID (GET)
GET http://localhost:3000/sales/1

### Crear una nueva venta (POST)
POST http://localhost:3000/sales
Content-Type: application/json

{
  "client_rfc": "2132131",
    "product_id": 1,
    "quantity": 10,
    "sale_date": "2024-11-24T16:00:00",
    "payment_method": "debit",
    "ticket": "TICKET1",
    "invoice": "INV1"
}


### Actualizar una venta existente 
PUT http://localhost:3000/sales/1
Content-Type: application/json

{
    "client_rfc": "21350239",
    "product_id": 2,
    "quantity": 3,
    "sale_date": "2024-11-23T17:32:00",
    "payment_method": "cash",
    "ticket": "TICKET1",
    "invoice": "INV1"
}

### Eliminar una venta (DELETE)
DELETE http://localhost:3000/sales/1