GET http://localhost:3000/usuarios

### 
GET http://localhost:3000/usuarios/5

### 
POST http://localhost:3000/usuarios/ 
content-type: application/json

{
"nombre": "Jesus", 
"apellidos": "Garcia", 
"email": "garciagg1090@gmail.com"
}

###
PUT http://localhost:3000/usuarios/2
content-type: application/json

{
  "nombre": "Juan", 
"apellidos": "Cervantes", 
"email": "juanervantes742@gmail.com"  
}