POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "uri1090@gmail.com",
    "password": "garcia123?"
}

###
GET http://localhost:3000/users/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzM0MDIyODAwLCJleHAiOjE3MzQwMjMxMDB9.KNKp4PyQkcmOkG69Pmgz0Q7qiUJ24e6-7g-RlEkhEVw