GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzM0MDIyODAwLCJleHAiOjE3MzQwMjMxMDB9.KNKp4PyQkcmOkG69Pmgz0Q7qiUJ24e6-7g-RlEkhEVw
###
GET http://localhost:3000/users/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzM0MDIyODAwLCJleHAiOjE3MzQwMjMxMDB9.KNKp4PyQkcmOkG69Pmgz0Q7qiUJ24e6-7g-RlEkhEVw
###
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiaWF0IjoxNzM0MDIzMTY4LCJleHAiOjE3MzQwMjM0Njh9.ivzj1BxGne8j1bXsF77dqXC65QXj1tAzY4JXVsFdarg

{
    "first_name": "Dennis",
    "last_name": "Bmx",
    "email": "bmx@gmail.com",
    "password": "bici123?"
}

###

PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "first_name": "Jesus",
    "last_name": "Castillo",
    "email": "castillo@gmail.com"
}

###

DELETE http://localhost:3000/users/2