GET http://localhost:3000/users

###
GET http://localhost:3000/users/1


###
POST http://localhost:3000/users
Content-Type: application/json

{
    "first_name": "Uriel",
    "last_name": "Alberto",
    "email": "uri1090@gmail.com",
    "password": "garcia123?"
}

###

PUT http://localhost:3000/users/1
Content-Type: application/json

{
    "first_name": "Jesus",
    "last_name": "Castillo",
    "email": "castillo@gmail.com"
}

###

DELETE http://localhost:3000/users/2